D:/Conda_Envs/lite-mono/python.exe train.py `
  --dataset citrus `
  --split citrus_prepared `
  --data_path citrus_project/dataset_workspace `
  --model lite-mono `
  --model_name structure_aware_label_free_vegetation_depth_b12_30ep_full `
  --log_dir citrus_project/milestones/04_lightweight_vegetation_improvement/levinson/runs `
  --mypretrain weights/lite-mono/lite-mono-pretrain.pth `
  --weights_init pretrained `
  --batch_size 12 `
  --num_epochs 30 `
  --lr 0.0001 0.000005 31 0.0001 0.00001 31 `
  --weight_decay 0.01 `
  --drop_path 0.2 `
  --height 192 `
  --width 640 `
  --num_workers 0 `
  --log_frequency 100 `
  --save_frequency 1 `
  --seed 0 `
  --teacher_structure_regularization `
  --teacher_structure_weight 0.03 `
  --teacher_structure_warmup_steps 500 `
  --teacher_structure_decay 0.5 `
  --teacher_gradient_loss `
  --teacher_gradient_weight 0.01 `
  --teacher_ranking_loss `
  --teacher_ranking_weight 0.02 `
  --teacher_rank_samples 512 `
  --teacher_path weights/lite-mono `
  --structure_aware_teacher `
  --structure_edge_boost_weight 0.75 `
  --structure_rgb_edge_threshold 0.08 `
  --structure_rgb_edge_ramp 0.08 `
  --structure_teacher_edge_threshold 0.03 `
  --structure_teacher_edge_ramp 0.03 `
  --structure_edge_dilation 5 `
  --sky_far_structure_loss `
  --sky_far_weight 0.005 `
  --sky_far_margin 0.08 `
  --sky_top_fraction 0.45 `
  --sky_lower_reference_start 0.55 `
  --sky_blue_margin 0.02 `
  --sky_confidence_temperature 0.08 `
  --sky_min_brightness 0.20 `
  --sky_min_saturation 0.04 `
  --sky_min_ratio 0.005
